from __future__ import annotations

# Timezone
SESSION_TIMEZONE = "America/New_York"

# Session windows
PRIMARY_SESSION_START = "09:35"
PRIMARY_SESSION_END = "11:00"
SECONDARY_SESSION_START = "13:30"
SECONDARY_SESSION_END = "15:00"
HARD_EOD_EXIT_TIME = "15:30"

# Opening range definition
OPENING_RANGE_BARS = 5
OPENING_RANGE_BAR_SIZE = "1m"

# ORB entry conditions
ORB_VOLUME_MULTIPLIER = 1.3
ORB_PRIOR_DAY_CLEARANCE_ATR = 1.5
ORB_MAX_EXTENSION_PCT = 0.01

# VWAP setup conditions
VWAP_MESSY_TEST_COUNT = 3
VWAP_INITIAL_DRIVE_MIN_PCT = 0.003

# Pullback continuation conditions
PULLBACK_MAX_RETRACE_RATIO = 0.50
PULLBACK_MIN_TREND_BARS = 3

# Sweep reversal conditions
SWEEP_MAX_BREACH_PCT = 0.005
SWEEP_SNAP_BARS = 2
TREND_DAY_EXTENSION_PCT = 0.015

# Take profit
R_TARGET_PARTIAL = 1.5
R_TARGET_MAIN = 2.0

# Instrument dollars-per-point
MES_DOLLARS_PER_POINT = 5.0
MNQ_DOLLARS_PER_POINT = 2.0

# Strategy weights by tier
WEIGHT_MICRO_STARTER_PRO_GROWTH = 0.09
WEIGHT_SCALE = 0.05

# Setup family priority
SETUP_PRIORITY = {
    "ORB": 1,
    "VWAP_RECLAIM": 2,
    "VWAP_REJECTION": 2,
    "PULLBACK_CONTINUATION": 3,
    "SWEEP_REVERSAL": 4,
}

# Setup valid windows
ORB_VALID_UNTIL_MINUTES_AFTER_OPEN = 45
SWEEP_VALID_UNTIL_MINUTES_AFTER_OPEN = 60

# Deterministic skip reason codes
SKIP_OUTSIDE_PRIMARY_WINDOW = "SKIP_OUTSIDE_PRIMARY_WINDOW"
SKIP_OUTSIDE_SECONDARY_WINDOW = "SKIP_OUTSIDE_SECONDARY_WINDOW"
SKIP_EOD_FLATTEN_WINDOW = "SKIP_EOD_FLATTEN_WINDOW"
SKIP_INSUFFICIENT_BARS = "SKIP_INSUFFICIENT_BARS"
SKIP_ORB_VOLUME_TOO_LOW = "SKIP_ORB_VOLUME_TOO_LOW"
SKIP_ORB_TOO_EXTENDED = "SKIP_ORB_TOO_EXTENDED"
SKIP_ORB_NO_CLEARANCE = "SKIP_ORB_NO_CLEARANCE"
SKIP_VWAP_MESSY = "SKIP_VWAP_MESSY"
SKIP_VWAP_NO_INITIAL_DRIVE = "SKIP_VWAP_NO_INITIAL_DRIVE"
SKIP_PULLBACK_TOO_DEEP = "SKIP_PULLBACK_TOO_DEEP"
SKIP_PULLBACK_TREND_NOT_CONFIRMED = "SKIP_PULLBACK_TREND_NOT_CONFIRMED"
SKIP_SWEEP_TOO_DEEP = "SKIP_SWEEP_TOO_DEEP"
SKIP_SWEEP_NO_SNAPBACK = "SKIP_SWEEP_NO_SNAPBACK"
SKIP_SWEEP_TREND_DAY = "SKIP_SWEEP_TREND_DAY"
SKIP_STOP_TOO_WIDE = "SKIP_STOP_TOO_WIDE"
SKIP_TIER_ENFORCEMENT = "SKIP_TIER_ENFORCEMENT"
SKIP_PRIORITY_SUPPRESSED = "SKIP_PRIORITY_SUPPRESSED"
SKIP_DUPLICATE_SIGNAL = "SKIP_DUPLICATE_SIGNAL"
