"""chad.validation — the offline edge-validation harness (isolated package).

Hard isolation guarantee (SSOT §2): nothing in this package may import the live
trading loop, broker adapters, or any ``runtime/`` reader, and nothing in the
live trading path may import this package. Phase 0 (``bar_audit``) is the
forensic data-quality gate: no bar is backtested until it has been audited.

Public API is re-exported here so later phases embed the data-quality section by
importing from :mod:`chad.validation` rather than reaching into submodules.
"""

from __future__ import annotations

from chad.validation.bar_audit import (
    AuditConfig,
    CorpusAudit,
    Finding,
    Status,
    SymbolAudit,
    audit_bar_file,
    audit_corpus,
    audit_symbol,
    render_corpus_summary,
    render_symbol_audit,
)
from chad.validation.cost_model import (
    CostBreakdown,
    CostConfig,
    DEFAULT_COST_CONFIG,
    InstrumentClass,
    IntrabarResolution,
    LiquidityTier,
    Trade,
    apply_costs,
    resolve_intrabar,
)
from chad.validation.regime_labeler import (
    DEFAULT_REGIME_CONFIG,
    Regime,
    RegimeConfig,
    RegimeLabel,
    RegimeSeries,
    label_series,
)
from chad.validation.scoring_spine import (
    DEFAULT_PERIODS_PER_YEAR,
    ScoreResult,
    equity_to_returns,
    score_equity,
    score_returns,
    score_trades,
)
from chad.validation.significance import (
    DEFAULT_RUIN_CONFIG,
    DEFAULT_SEED_SET,
    DEFAULT_TRIAL_MULTIPLE,
    EULER_MASCHERONI,
    DeflatedSharpeResult,
    RuinConfig,
    RuinResult,
    SeedSweepResult,
    deflated_sharpe_ratio,
    estimate_ruin,
    expected_max_sharpe,
    per_period_sharpe,
    probabilistic_sharpe_ratio,
    punitive_trial_count,
    sample_kurtosis,
    sample_skewness,
    seed_sweep,
    time_average_growth_rate,
    worst_quantile,
)
from chad.validation.splits import (
    Partition,
    WalkForwardWindow,
    generate_walk_forward,
    partition,
)
from chad.validation.feature_parity import (
    DEFAULT_SIGNAL_CATALOG,
    DetectedInput,
    FeatureParityResult,
    InputCategory,
    InputSignal,
    ParityStatus,
    audit_heads,
    classify_head_file,
    classify_source,
    is_backtestable,
    render_parity_summary,
)
from chad.validation.backtest_engine import (
    DEFAULT_EXECUTION_SPEC,
    Bar,
    BacktestResult,
    BarWindow,
    DecisionRecord,
    ExecutionSpec,
    LookaheadError,
    Signal,
    SyntheticTrade,
    TrackScore,
    load_bars_file,
    prepare_bars,
    replay_decisions,
    run_backtest,
)
from chad.validation.oos_lockbox import (
    ACCESS_LOG_FILENAME,
    DEFAULT_DECOY_SEED,
    SEAL_FILENAME,
    OOSAccessError,
    OOSAccessRecord,
    OOSLockbox,
    OOSSeal,
    OOSSealError,
    returns_hash,
    synthetic_decoy_returns,
)
from chad.validation.config_freeze import (
    LEDGER_FILENAME,
    FreezeLedger,
    FreezeState,
    FrozenConfig,
    config_hash,
    deflation_trials,
)
from chad.validation.verdict import (
    DEFAULT_THRESHOLDS,
    N_MIN,
    PASS_LABEL,
    R_MIN,
    W_MIN,
    CheckOutcome,
    HeadMetrics,
    PortfolioMetrics,
    Verdict,
    VerdictResult,
    VerdictThresholds,
    decide_portfolio_verdict,
    decide_verdict,
)
from chad.validation.report_writer import (
    SCHEMA_VERSION,
    SIGNATURE_ALGO,
    UNIVERSE_PROVENANCE_NOTE,
    build_report,
    render_markdown,
    report_basename,
    sign_report,
    verify_signature,
    write_report,
)
from chad.validation.trade_log_adapter import (
    AdapterManifest,
    AdapterResult,
    AdmittedTrade,
    adapt_records,
    classify_instrument,
    is_placeholder_fill,
    iter_ledger_files,
    run_adapter,
    trust_exclusion,
)

__all__ = [
    "AuditConfig",
    "CorpusAudit",
    "Finding",
    "Status",
    "SymbolAudit",
    "audit_bar_file",
    "audit_corpus",
    "audit_symbol",
    "render_corpus_summary",
    "render_symbol_audit",
    # Phase 1 — shared scoring spine (SSOT §1.3).
    "DEFAULT_PERIODS_PER_YEAR",
    "ScoreResult",
    "equity_to_returns",
    "score_equity",
    "score_returns",
    "score_trades",
    # Phase 2 — cost model + pessimistic execution (SSOT §3.5).
    "CostBreakdown",
    "CostConfig",
    "DEFAULT_COST_CONFIG",
    "InstrumentClass",
    "IntrabarResolution",
    "LiquidityTier",
    "Trade",
    "apply_costs",
    "resolve_intrabar",
    # Phase 2 — splits + purged/embargoed walk-forward (SSOT §3.7).
    "Partition",
    "WalkForwardWindow",
    "generate_walk_forward",
    "partition",
    # Phase 2 — independent regime labeler (SSOT §3.4).
    "DEFAULT_REGIME_CONFIG",
    "Regime",
    "RegimeConfig",
    "RegimeLabel",
    "RegimeSeries",
    "label_series",
    # Phase 3 — significance (deflated Sharpe) + ruin/ergodicity (SSOT §3.3/§3.6).
    "DEFAULT_RUIN_CONFIG",
    "DEFAULT_SEED_SET",
    "DEFAULT_TRIAL_MULTIPLE",
    "EULER_MASCHERONI",
    "DeflatedSharpeResult",
    "RuinConfig",
    "RuinResult",
    "SeedSweepResult",
    "deflated_sharpe_ratio",
    "estimate_ruin",
    "expected_max_sharpe",
    "per_period_sharpe",
    "probabilistic_sharpe_ratio",
    "punitive_trial_count",
    "sample_kurtosis",
    "sample_skewness",
    "seed_sweep",
    "time_average_growth_rate",
    "worst_quantile",
    # Phase 4 — feature-parity gate (SSOT §V1): REPLAYABLE / NOT_REPLAYABLE / UNKNOWN.
    "DEFAULT_SIGNAL_CATALOG",
    "DetectedInput",
    "FeatureParityResult",
    "InputCategory",
    "InputSignal",
    "ParityStatus",
    "audit_heads",
    "classify_head_file",
    "classify_source",
    "is_backtestable",
    "render_parity_summary",
    # Phase 4 — Stage-1 historical backtest engine (SSOT §3.5 / §3.8 / Part 2).
    "DEFAULT_EXECUTION_SPEC",
    "Bar",
    "BacktestResult",
    "BarWindow",
    "DecisionRecord",
    "ExecutionSpec",
    "LookaheadError",
    "Signal",
    "SyntheticTrade",
    "TrackScore",
    "load_bars_file",
    "prepare_bars",
    "replay_decisions",
    "run_backtest",
    # Phase 5 — OOS lockbox (SSOT §3.1): hash-seal + --final-run gate + access log.
    "ACCESS_LOG_FILENAME",
    "DEFAULT_DECOY_SEED",
    "SEAL_FILENAME",
    "OOSAccessError",
    "OOSAccessRecord",
    "OOSLockbox",
    "OOSSeal",
    "OOSSealError",
    "returns_hash",
    "synthetic_decoy_returns",
    # Phase 5 — config freeze (SSOT §3.2): hash-freeze + post-FAIL trial penalty.
    "LEDGER_FILENAME",
    "FreezeLedger",
    "FreezeState",
    "FrozenConfig",
    "config_hash",
    "deflation_trials",
    # Phase 5 — verdict (SSOT Part 4): PASS(candidate)/FAIL/INSUFFICIENT_DATA/…
    "DEFAULT_THRESHOLDS",
    "N_MIN",
    "PASS_LABEL",
    "R_MIN",
    "W_MIN",
    "CheckOutcome",
    "HeadMetrics",
    "PortfolioMetrics",
    "Verdict",
    "VerdictResult",
    "VerdictThresholds",
    "decide_portfolio_verdict",
    "decide_verdict",
    # Phase 5 — report writer (SSOT Part 4 / §3.8): signed edge_report artifact.
    "SCHEMA_VERSION",
    "SIGNATURE_ALGO",
    "UNIVERSE_PROVENANCE_NOTE",
    "build_report",
    "render_markdown",
    "report_basename",
    "sign_report",
    "verify_signature",
    "write_report",
    # Phase 6 — Stage-2 real-trade ingest adapter (SSOT §1.3 / Part 6): trust gate + manifest.
    "AdapterManifest",
    "AdapterResult",
    "AdmittedTrade",
    "adapt_records",
    "classify_instrument",
    "is_placeholder_fill",
    "iter_ledger_files",
    "run_adapter",
    "trust_exclusion",
]
